-- begin BURGER_ORDER_ITEM
alter table BURGER_ORDER_ITEM add constraint FK_BURGER_ORDER_ITEM_MENU_ITEM foreign key (MENU_ITEM_ID) references BURGER_MENU_ITEM(ID)^
alter table BURGER_ORDER_ITEM add constraint FK_BURGER_ORDER_ITEM_ORDER foreign key (ORDER_ID) references BURGER_ORDER(ID)^
create index IDX_BURGER_ORDER_ITEM_MENU_ITEM on BURGER_ORDER_ITEM (MENU_ITEM_ID)^
create index IDX_BURGER_ORDER_ITEM_ORDER on BURGER_ORDER_ITEM (ORDER_ID)^
-- end BURGER_ORDER_ITEM
-- begin BURGER_ORDER
alter table BURGER_ORDER add constraint FK_BURGER_ORDER_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BURGER_ORDER_USER on BURGER_ORDER (USER_ID)^
-- end BURGER_ORDER
-- begin BURGER_MENU_ITEM
alter table BURGER_MENU_ITEM add constraint FK_BURGER_MENU_ITEM_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_BURGER_MENU_ITEM_IMAGE on BURGER_MENU_ITEM (IMAGE_ID)^
-- end BURGER_MENU_ITEM
